[package]
name = "frame_admin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[registries.crates-io]
protocol = "sparse"  # requires Rust 1.68

[dependencies]
chrono = "0.4.24"
dotenv = "0.15.0"
env_logger = "0.10.0"
image = { version = "0.24.6", features = ["jpeg"] }
lazy_static = "1.4.0"
log = "0.4.17"
rand = "0.8.5"
serde = { version = "1.0.158", features = ["derive"] }
tera = { version = "1.18.1", default-features = false }
tiny_http = "0.12.0"
ureq = { version = "2.6.2", features = ["json"] }
url = "2.3.1"
